# Generated by Django 6.0.3 on 2026-04-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('category', models.CharField(default='', max_length=50, verbose_name='产品类别')),
                ('spec', models.CharField(default='', max_length=50, verbose_name='规格')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价(元)')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品管理',
                'db_table': 'sales_product',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='代理点名称')),
                ('district', models.CharField(default='', max_length=50, verbose_name='区域')),
                ('city', models.CharField(default='广州', max_length=50, verbose_name='城市')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域管理',
                'db_table': 'sales_region',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='销售日期')),
                ('quantity', models.IntegerField(default=0, verbose_name='销售数量(支)')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价(元)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='销售金额(元)')),
                ('channel', models.CharField(choices=[('online', '线上电商'), ('offline', '线下门店'), ('distributor', '经销商')], default='offline', max_length=20, verbose_name='渠道')),
                ('remark', models.CharField(default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '销售记录',
                'verbose_name_plural': '销售记录管理',
                'db_table': 'sales_salesrecord',
                'ordering': ['-sale_date', '-id'],
            },
        ),
    ]
