# Generated by Django 6.0.3 on 2026-04-06 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.region', verbose_name='区域'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['sale_date'], name='sales_sales_sale_da_1e567b_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['product'], name='sales_sales_product_cb293f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['region'], name='sales_sales_region__3e8faf_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['channel'], name='sales_sales_channel_3bb7d9_idx'),
        ),
    ]
